language: ruby

rvm:
  - 2.3.3
  
sudo: required

before_install:
  - sudo apt-get install -y tree
  - sudo apt-get install -y sed
  - sudo add-apt-repository -y ppa:chris-lea/node.js 
  - sudo apt-get update
  - sudo apt-get install -y nodejs
  - sudo npm install -g gulp 

script:
  - printf "$(tree /home/travis/build/)" 
  - git clone -b develop https://$USER_TOKEN@github.com/mercadolibre/devsite-engine.git  
  - mkdir /home/travis/build/mercadolibre 
  - sudo mv devsite-engine /home/travis/build/mercadolibre/devsite-engine  
  - printf "$(tree /home/travis/build/)" 
  - rm -rf /home/travis/build/mercadolibre/devsite-engine/source
  - (cd /home/travis/build/mercadolibre/devsite-engine && git clone -b develop https://$USER_TOKEN@github.com/mercadopago/devsite-frontend.git source)
  - cp -R /home/travis/build/mercadopago/devsite-docs /home/travis/build/mercadolibre/devsite-engine/source/docs  
  - printf "$(pwd)"
  - printf "$(ls -la)"
  - printf "$(tree /home/travis/build/)" 
   
  