language: ruby

rvm:
  - 2.3.3
node_js:
  - 7
  
sudo: required

branches:
  only:
    - master

before_install:
  - sudo apt-get install -y tree
  - sudo apt-get install -y sed
  - sudo add-apt-repository -y ppa:chris-lea/node.js 
  - sudo apt-get update   
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  - source ~/.profile
  - echo "$(nvm --version)"
  - nvm install node
  
install: 
  - git clone -b develop https://$USER_TOKEN@github.com/mercadolibre/devsite-engine.git  
  - mkdir /home/travis/build/mercadolibre 
  - sudo mv devsite-engine /home/travis/build/mercadolibre/devsite-engine   
  - rm -rf /home/travis/build/mercadolibre/devsite-engine/source
  - (cd /home/travis/build/mercadolibre/devsite-engine && git clone -b develop https://$USER_TOKEN@github.com/mercadopago/devsite-frontend.git source)
  - cp -R /home/travis/build/mercadopago/devsite-docs /home/travis/build/mercadolibre/devsite-engine/source/docs
  - (nvm use node && cd /home/travis/build/mercadolibre/devsite-engine/source && npm install gulp)
  - (cd /home/travis/build/mercadolibre/devsite-engine/ && bundle install)
  - git config --global user.name "devsite bot"
script:
  - (nvm use node latest && cd /home/travis/build/mercadolibre/devsite-engine/source && gulp deploy)
  - (nvm use node && cd /home/travis/build/mercadolibre/devsite-engine && TARGET=test middleman deploy) 
   
  